### ISSUE TITLE
verbosity level for settings

### ISSUE THREAD

**Issue by kaat0** [railtoolkit/TrainRuns.jl#10]

**Comment by apriljunge** [comment]
I would suggest to use [julia logging](https://docs.julialang.org/en/v1/stdlib/Logging/) ([More info](https://julialogging.github.io/)) and not introducing another setting option.
Using this logging it would respect multiple possibilities to define the loglevel and if you want to log to a file or stdout, ...

**Comment by kaat0** [comment]
- [ ] convert `println()` into `@info`, `@warn`, `@error` messages

**Comment by kaat0** [comment]
I have mainly implemented the verbosity setting so that Julia logging is used. In the past, Max and I have simply ignored it. I assume that when other people with little Julia experience come along, they will feel the same way. It helps if there are accesses to logging mechanisms that also exist in other programming worlds. For example, in the CLI world with Bash & co. 

It also helps if the input and output of programs are reproducible. The trait of reproducibility includes that there is only one file with environment variables, currently `Settings()`.

The other possibility would be storing the settings in a Julia-style environment.

**Comment by kaat0** [comment]
See comment by @apriljunge https://github.com/railtoolkit/TrainRuns.jl/commit/e72c55ff11f080a830210f1010aacc9882c98e34#commitcomment-142392830

**Comment by kaat0** [comment]
I thought about introducing a extended logging based on [common levels](https://en.wikipedia.org/wiki/Java_logging_framework#Severity_level):
```
fatal: 3000,
error: 2000,
warn: 1000,
info: 0
debug: -1000
trace: -2000
```

[I am not the only one](https://github.com/JuliaLang/julia/issues/33418) with the impulse and "need".

After watching [Logging in Julia@ JuliaCon 2023](https://www.youtube.com/watch?v=G9eZh0CxKgo), I guess we have to be flexible for future changes in the Julia Logging Framework.

**Comment by kaat0** [comment]
see [LoggingExtras.jl/issues/91](https://github.com/JuliaLogging/LoggingExtras.jl/issues/91)
