### ISSUE TITLE
Output of POIs without POIs in the path data - unexpected behaviour

### ISSUE THREAD

**Issue by kaat0** [railtoolkit/TrainRuns.jl#20]
With
```
path     = Path("data/paths/realworld.yaml")
train    = Train("local_train.yaml")
settings = Settings(outputDetail=:points_of_interest)
run      = trainrun(train, path, settings)
```
the DataFrame of run contains outputDetail=:driving_course, which is misleading as to the settings.

I suggest two options:
1. Introducing default labels for `departure` and `arrival` could give rows as an output.
2. return an empty DataFrame.

**Comment by MaxKannenberg** [comment]
The issue has been resolved with commit 5e33e62a79c78513dcea0a9ca65b87376a8fb669
The output for outputDetail=:points_of_interest for a path without points_of_interest has been changed. Now the output consists of the first and the last support point of the driving course with information of depature and arrival.
