### ISSUE TITLE
Clarify the need for name, id and uuid for Path

### ISSUE THREAD

**Issue by apriljunge** [railtoolkit/TrainRuns.jl#48]
Are they even used? Wouldn't it be enough to have only one of them?

**Comment by kaat0** [comment]
The usage of `name`, `id` and `UUID` depends on your project organisation. But I do agree that probably one identifier is enough (preferably the `UUID`) and that the `name` can be renamed into `description`.

Please see [schema/issues/5](https://github.com/railtoolkit/schema/issues/5).

**Comment by kaat0** [comment]
The usage of `name`, `id` and `UUID` depends on your project organisation. But I do agree that probably one identifier is enough (preferably the `UUID`) and that the `name` can be renamed into `description`.

Please see [schema/issues/5](https://github.com/railtoolkit/schema/issues/5).
