### ISSUE TITLE
Only one POI is calculated of POIs with the same position

### ISSUE THREAD

**Issue by apriljunge** [railtoolkit/TrainRuns.jl#56]
If two POIs have the same position (calculated position `s`) , only one POI is returned. The others are omitted without any warning.

**Comment by kaat0** [comment]
Would you prefer a warning or a double entry at the position in the trainrun Dataframe?

**Comment by apriljunge** [comment]
The best way would be to keep all entrys.

Think of making multiple calculations with different train lengths. On some trains pois could be omitted, when the calculated position `s` of a `front` poi and a `rear` poi are the same.
