### ISSUE TITLE
Behaviour at start of track

### ISSUE THREAD

**Issue by apriljunge** [railtoolkit/TrainRuns.jl#58]
When calculating with `outputDetail=:data_points` the start of the track is heavily dependent on the `stepSize`.
With `stepsize=20` _(default)_ its like this:

|  | driving_mode | s |
|--------|--------|--------|
| 1 | "breakFree" | 0.0 |
| 2 | "accelerating" | **20.0** |

With `stepsize=1` its like this:

|  | driving_mode | s |
|--------|--------|--------|
| 1 | "breakFree" | 0.0 |
| 2 | "accelerating" | **1.0** |

Wouldnt it be correct to accelerate always at the start? Like this:
|  | driving_mode | s |
|--------|--------|--------|
| 1 | "breakFree" | 0.0 |
| 2 | "accelerating" | **0.0** |

**Comment by kaat0** [comment]
"breakFree" is the first iteration of the calculation and therefore already an acceleration. Hence the next entry depends on the `stepsize`. "breakFree" is handled like an acceleration and serves as a reminder that the first iteration is somehow special concerning the values of the calculation.

To my knowledge, there is currently no proven and, therefore, correct way to calculate the "breakFree" phase of trains. Nonetheless, the "breakFree" phase does exist physically and is somehow "magic", depending on the age of the train, the bearings, the length, the weather, the slope, the skill of the driver, etc. It is the first resistance to overcome.
