### ISSUE TITLE
Contributions

### ISSUE THREAD

**Issue by kaat0** [railtoolkit/TrainRuns.jl#64]
Added the Bot [all-contributors](https://allcontributors.org/) to the repo.

**Comment by kaat0** [comment]
See list of [contributions](https://allcontributors.org/docs/en/emoji-key).

**Comment by kaat0** [comment]
https://github.com/all-contributors
please add @MaxKannenberg for code.
please add @MaxKannenberg for ideas.
please add @MaxKannenberg for maintenance.
please add @MaxKannenberg for research.
please add @apriljunge for bug.
please add @apriljunge for content.
please add @apriljunge for doc.
please add @apriljunge for ideas.
please add @apriljunge for maintenance.
please add @apriljunge for question.
please add @apriljunge for research.
please add @kaat0 for code.
please add @kaat0 for ideas.
please add @kaat0 for maintenance.
please add @kaat0 for research.
please add @kaat0 for data.
please add @kaat0 for research.
please add @kaat0 for tool.
please add @kaat0 for test.
please add @kaat0 for tutorial.
please add @kaat0 for mentoring.

**Comment by kaat0** [comment]
@all-contributors
please add @MaxKannenberg for code.
please add @MaxKannenberg for ideas.
please add @MaxKannenberg for maintenance.
please add @MaxKannenberg for research.
please add @kaat0 for code.
please add @kaat0 for ideas.
please add @kaat0 for maintenance.
please add @kaat0 for research.
please add @kaat0 for data.
please add @kaat0 for research.
please add @kaat0 for tool.
please add @kaat0 for test.
please add @kaat0 for tutorial.
please add @kaat0 for mentoring.
please add @apriljunge for bug.
please add @apriljunge for content.
please add @apriljunge for doc.
please add @apriljunge for ideas.
please add @apriljunge for maintenance.
please add @apriljunge for question.
please add @apriljunge for research.

**Comment by kaat0** [comment]
The use of [multiple lines](https://allcontributors.org/docs/en/bot/usage#using-multiple-lines) did not work as anticipated.

**Comment by kaat0** [comment]
- [ ] add [.all-contributorsrc](https://github.com/railtoolkit/TrainRuns.jl/blob/main/.all-contributorsrc) to the ignore list in [CI.yml](https://github.com/railtoolkit/TrainRuns.jl/blob/main/.github/workflows/CI.yml)

**Comment by kaat0** [comment]
@all-contributors please add @MaxKannenberg for code. please add @kaat0 for code.

**Comment by kaat0** [comment]
https://github.com/all-contributors please add @MaxKannenberg for ideas

**Comment by kaat0** [comment]
@all-contributors please add @MaxKannenberg for ideas

**Comment by kaat0** [comment]
@all-contributors please add @MaxKannenberg for maintenance

**Comment by kaat0** [comment]
@all-contributors
please add @kaat0 for code.
please add @kaat0 for ideas.
please add @kaat0 for maintenance.
please add @kaat0 for research.
please add @kaat0 for data.
please add @kaat0 for research.
please add @kaat0 for tool.
please add @kaat0 for test.
please add @kaat0 for tutorial.
please add @kaat0 for mentoring.

**Comment by kaat0** [comment]
@all-contributors
please add @kaat0 for code.
please add @kaat0 for ideas.
please add @kaat0 for maintenance.
please add @kaat0 for research.
please add @kaat0 for data.
please add @kaat0 for research.
please add @kaat0 for tool.
please add @kaat0 for test.
please add @kaat0 for tutorial.

**Comment by kaat0** [comment]
@all-contributors
please add @kaat0 for code.

**Comment by kaat0** [comment]
@all-contributors 
please add @kaat0 for ideas.  
please add @kaat0 for maintenance. 
 please add @kaat0 for research. 
 please add @kaat0 for data.  
please add @kaat0 for research.  
please add @kaat0 for tool.  
please add @kaat0 for test.

**Comment by kaat0** [comment]
@all-contributors 
please add @kaat0 for ideas. 
please add @kaat0 for maintenance.
 please add @kaat0 for research.
 please add @kaat0 for data. 
please add @kaat0 for research. 
please add @kaat0 for tool.

**Comment by kaat0** [comment]
@all-contributors 
please add @kaat0 for ideas. 
please add @kaat0 for maintenance.
 please add @kaat0 for research.
 please add @kaat0 for data. 
please add @kaat0 for research.

**Comment by kaat0** [comment]
@all-contributors 
please add @kaat0 for ideas. 
please add @kaat0 for maintenance.
 please add @kaat0 for data.

**Comment by kaat0** [comment]
@all-contributors 
please add @kaat0 for ideas. 
please add @kaat0 for maintenance.

**Comment by kaat0** [comment]
@all-contributors 
please add @kaat0 for ideas.

**Comment by kaat0** [comment]
@all-contributors
please add @apriljunge for bug.
please add @apriljunge for content.
please add @apriljunge for doc.
please add @apriljunge for ideas.
please add @apriljunge for maintenance.
please add @apriljunge for question.

**Comment by kaat0** [comment]
@all-contributors
please add @apriljunge for bug.
please add @apriljunge for content.
please add @apriljunge for doc.
please add @apriljunge for ideas.

**Comment by kaat0** [comment]
@all-contributors
please add @apriljunge for bug.
please add @apriljunge for content.
please add @apriljunge for doc.

**Comment by kaat0** [comment]
@all-contributors
please add @apriljunge for bug.

**Comment by kaat0** [comment]
@apriljunge please feel free to add more contributions on your side!

**Comment by apriljunge** [comment]
Looks just fine. I think we can close this :)
